Controllers/ExportController.cs
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Services;
using Microsoft.AspNetCore.Mvc;
using StundenplanImport.Model;
using StundenplanImport.Model.Export;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace StundenplanImport.Controllers
{
    public class ExportController : Controller
    {
        /*
        public async Task<IActionResult> GoogleCalendar(TimetableKind kind, string timetableName, ICollection<Model.Lesson> lessons)
        {
            return View("Success");
        }
        */

        public async Task<IActionResult> ICalendar(TimetableKind kind, string timetableName, ICollection<Model.Lesson> lessons)
        {
            var exporter = new ExporterICalendar();
            
            var file = await exporter.ExportAsync(kind, timetableName, lessons);
            ViewData["File"] = file;

            return View("SuccessICalendar");
        }

        public FileResult Download(string fileName)
        {
            var path = Path.Combine("Static", "ICalendar", fileName + ".ics");
            
            var bytes = System.IO.File.ReadAllBytes(path);
            System.IO.File.Delete(path);
                
            return File(bytes, "text/calendar", "Stundenplan.ics");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StundenplanImport.Model.GesaHu;
using StundenplanImport.Model;
using StundenplanImport.Model.ViewModel;
using StundenplanImport.Model.Export;

namespace StundenplanImport.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var classes = (string[])Names.Classes.Clone();
            Array.Sort(classes);
            ViewData["Classes"] = classes;

            var students = (string[])Names.Students.Clone();
            Array.Sort(students);
            ViewData["Students"] = students;

            var teacherShorts = (string[])Names.Teachers.Clone();
            Array.Sort(teacherShorts);
            var teachers = new Tuple<string, string>[teacherShorts.Length];
            for(int i = 0; i < teacherShorts.Length; i++)
            {
                teachers[i] = Tuple.Create(teacherShorts[i], Names.ResolveTeacher(teacherShorts[i]));
            }
            ViewData["Teachers"] = teachers;

            return View();
        }

        public async Task<IActionResult> Edit(string @class, string student, string teacher)
        {
            TimetableKind kind = TimetableKind.Class;
            string element = "";

            if (!string.IsNullOrWhiteSpace(@class))
            {
                kind = TimetableKind.Class;
                element = @class;
            }
            else if (!string.IsNullOrWhiteSpace(teacher))
            {
                kind = TimetableKind.Teacher;
                element = teacher;
            }
            else if (!string.IsNullOrWhiteSpace(student))
            {
                kind = TimetableKind.Student;
                element = student;
            }

            TimetableLoader timetable = new TimetableLoader(kind, element);
            var lessons = await timetable.LoadAsync();

            var lessonVMs = new List<LessonViewModel>();
            foreach(var lesson in lessons)
            {
                var classVMs = new List<ClassViewModel>();
                foreach(var _class in lesson.Classes)
                {
                    classVMs.Add(new ClassViewModel(_class.Name, _class.Teacher, _class.Room));
                }
                lessonVMs.Add(new LessonViewModel(lesson.DayOfWeek, lesson.Period, lesson.Duration, lesson.Name, kind == TimetableKind.Teacher ? lesson.SchoolClass : lesson.Teacher, lesson.Room, lesson.Color, lesson.Week, classVMs));
            }

            var viewModel = new EditViewModel(kind, element, lessonVMs);

            return View(viewModel);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/LoginController.cs
using Google.Apis.Auth.OAuth2;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace StundenplanImport.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View("Login");
        }
        
        [AllowAnonymous]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            var props = new AuthenticationProperties
            {
                RedirectUri = "index",
            };
            
            return new ChallengeResult(provider, props);
        }
    }
}

Views/Export/SuccessICalendar.cshtml
@{
    ViewData["Title"] = "Import erfolgreich";
}

<div class="row">
    <div class="col-sm-6 col-xs-12">
        <h3>Import erfolgreich</h3>
        <a asp-controller="Export" asp-action="Download" asp-route-fileName="@ViewData["File"]" as target="_blank" download><button type="button" class="btn btn-success">Kalenderdatei herunterladen</button></a>
    </div>

    <div class="col-sm-6 col-xs-12">
        <h4>Die Datei importieren</h4>
        <ul>
            <li><a href="https://support.google.com/calendar/answer/37118?hl=de" target="_blank">Google Kalender</a></li>
            <li><a href="http://www.macwelt.de/tipps/iCloud-Kalender-importieren-und-zu-iCloud-hinzufuegen-6505205.html" target="_blank">iCloud Kalender</a></li>
            <li><a href="https://support.office.com/de-de/article/Importieren-oder-Abonnieren-eines-Kalenders-in-Outlook-com-oder-Outlook-im-Web-cff1429c-5af6-41ec-a5b4-74f2c278e98c?ui=de-DE&rs=de-DE&ad=DE#bkmk_newodcimport" target="_blank">Microsoft Kalender</a></li>
        </ul>
    </div>
</div>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Über";
}
<h2>@ViewData["Title"].</h2>

<p>Entwickelt von Robin Kertels</p>
<br />
<a href="https://github.com/K0bin/GesaHuStundenplan">GitHub</a>

Views/Home/Edit.cshtml
@{
    ViewData["Title"] = "Bearbeiten";
}

@using StundenplanImport.Model.GesaHu;
@using StundenplanImport.Model;

@model StundenplanImport.Model.ViewModel.EditViewModel

<div class="row">
    <div class="col-md-3 col-xs-6">
        <h5>Woche</h5>
    </div>
    <div class="col-md-3 col-xs-6">
        <div class="radio">
            <label>
                <input type="radio" name="week" id="week-radio-1" value="1" checked="" onchange="onChangeWeekRadioButton();">
                Gerade Woche
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="week" id="week-radio-2" value="2" onchange="onChangeWeekRadioButton();">
                Ungerade Woche
            </label>
        </div>
    </div>
</div>

<form asp-controller="Export" asp-action="ICalendar" method="post">
    <table class="table table-bordered timetable">
        <thead>
            <tr>
                <th></th>
                <th>Montag</th>
                <th>Dienstag</th>
                <th>Mittwoch</th>
                <th>Donnerstag</th>
                <th>Freitag</th>
            </tr>
        </thead>
        <tbody>
            @{
                int lessonCount = 0;
                for (int lessonRow = 0; lessonRow < 10; lessonRow++)
                {
                    <tr>
                        <td>@(lessonRow + 1)</td>
                        @for (int dayColumn = 0; dayColumn < 5; dayColumn++)
                        {
                            Week week = Week.None;

                            foreach (var lesson in Model.Lessons)
                            {
                                var dayOfWeek = (DayOfWeek)((int)DayOfWeek.Monday + dayColumn);
                                if (lesson.Day == dayOfWeek && lesson.Period == lessonRow)
                                {
                                    <td rowspan="@lesson.Duration.ToString()" id="cell-@(lessonCount)" class="week_@lesson.Week.ToString().ToLower()">
                                        <a id="" href="javascript:void(0)" onclick="onLessonRemoved(@(lessonCount));"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>

                                        <span class="subject">@lesson.Name<br />@lesson.TeacherOrSchoolClass<br />@lesson.Room</span>
                                        @if (lesson.Classes.Count > 1)
                                        {
                                            <select id="select-@(lessonCount)" class="selectpicker" onchange="onLessonClassSelected(@(lessonCount));">
                                                @foreach (var _class in lesson.Classes)
                                                {
                                                    <option value="@_class.ShortName-@_class.ShortTeacher-@_class.ShortRoom">@_class.Name @_class.Teacher @_class.Room</option>
                                                }
                                            </select>
                                        }

                                        <input name="lessons[@(lessonCount)].Week" type="hidden" value="@lesson.Week" />
                                        <input name="lessons[@(lessonCount)].Day" type="hidden" value="@lesson.Day" />
                                        <input name="lessons[@(lessonCount)].Period" type="hidden" value="@lesson.Period" />
                                        <input name="lessons[@(lessonCount)].Duration" type="hidden" value="@lesson.Duration" />
                                        <input name="lessons[@(lessonCount)].Name" type="hidden" value="@lesson.Name" id="name-@(lessonCount)" />
                                        <input name="lessons[@(lessonCount)].TeacherOrSchoolClass" type="hidden" value="@lesson.TeacherOrSchoolClass" id="teacher-@(lessonCount)" />
                                        <input name="lessons[@(lessonCount)].Room" type="hidden" value="@lesson.ShortRoom" id="room-@(lessonCount)" />
                                    </td>

                                    lessonCount++;

                                    if (week != Week.None)
                                    {
                                        week = Week.Both;
                                    }
                                    else
                                    {
                                        week = lesson.Week;
                                    }
                                }
                                else if (lesson.Day == dayOfWeek && lesson.Period == lessonRow - 1 && lesson.Duration > 1 )
                                {
                                    if (week != Week.None)
                                    {
                                        week = Week.Both;
                                    }
                                    else
                                    {
                                        week = lesson.Week;
                                    }
                                }
                            }

                            if (week != Week.Both)
                            {
                                if (week == Week.None)
                                {
                                    <td></td>
                                }
                                else
                                {
                                    if (week == Week.Even)
                                    {
                                        <td class="week_odd"></td>
                                    }
                                    else
                                    {
                                        <td class="week_even"></td>
                                    }
                                }

                            }
                        }
                    </tr>
                    }
                }
        </tbody>
    </table>

    <input name="timetableName" type="hidden" value="@Model.Element" />
    <input name="kind" type="hidden" value="@Model.Kind" />
    <input type="submit" />

</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Startseite";
}
@using StundenplanImport.Model

<div class="row">
    <div class="col-md-12">
        <h3>Wähle deinen Stundenplan aus:</h3>
    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-xs-12">
        <div class="row">
            <div class="col-sm-3 col-xs-6">
                <h5>Klasse</h5>
            </div>
            <div class="col-sm-3 col-xs-6">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Auswählen
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    @foreach (var entry in (string[])ViewData["Classes"])
            {
                        <li>@Html.ActionLink(entry, "edit", new { Class = entry })</li>
                    }
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3 col-xs-6">
                <h5>Schüler</h5>
            </div>

            <div class="col-sm-3 col-xs-6">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Auswählen
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    @foreach (var entry in (string[])ViewData["Students"])
        {
                        <li>@Html.ActionLink(entry, "edit", new { Student = entry })</li>
                    }
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3 col-xs-6">
                <h5>Lehrer</h5>
            </div>
            <div class="col-sm-3 col-xs-6">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Auswählen
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu3">
                    @foreach (var entry in (Tuple<string, string>[])ViewData["Teachers"])
                    {
                        <li>@Html.ActionLink(entry.Item2, "edit", new { Teacher = entry.Item1 })</li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

Views/Login/Login.cshtml
@{
    var loginProviders = Context.Authentication.GetAuthenticationSchemes().ToList();
    <form asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
        <div>
            <p>
                <button type="submit" class="btn btn-default" name="provider" value="Google" title="Google">Google</button>
            </p>
        </div>
    </form>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - GesaHu Stundenplan</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" />-->
    <link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css" />

    <!-- Bootstrap Select-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.0/css/bootstrap-select.min.css" />

    <environment names="Development">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="false" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">GStundenplan</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Startseite</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Über</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - GesaHu Stundenplan Importer</p>
        </footer>
    </div>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"></script>
    <environment names="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/site.js" asp-append-version="false"></script>
    </environment>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.0/js/bootstrap-select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.0/js/i18n/defaults-de_DE.min.js"></script>


    @RenderSection("scripts", required: false)
</body>
</html>